---
- name: set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: add new relic repo key
  apt_key:
    url: "{{ newrelic_php_repo_key_url }}"
    id: "{{ newrelic_php_repo_key_id }}"
    state: present

- name: add new relic repo
  apt_repository:
    repo: "{{ newrelic_php_repo }}"
    state: present
    filename: newrelic
  register: newrelic_repo

- name: apt-get update
  apt:
    update_cache: yes
  when: newrelic_repo.changed

- name: install newrelic php agent
  apt:
    pkg: "{{ newrelic_php_package }}"
    update_cache: yes
    cache_valid_time: 86400
    state: latest
