---
- name: check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: not newrelic_license_key|default(False)

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: default.yml
  when: not newrelic_loaded_os_family|default(False)

- name: configure newrelic agent
  template:
    src: newrelic.ini.j2
    dest: "{{ newrelic_config_path }}/newrelic.ini"
    group: root
    owner: root
    mode: 0644
  notify: restart newrelic
  when: newrelic_loaded_os_family|default(False)

- name: ensure new relic agent is started and enabled
  service:
    name: newrelic-daemon
    state: started
    enabled: true
