---
- name: set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: install new relic php agent
  yum:
    name: "{{ newrelic_php_package }}"
    state: latest
