---
- name: set newrelic_loaded_os_family
  set_fact:
    newrelic_loaded_os_family: "{{ ansible_os_family }}"

- name: Add repository
  yum_repository:
    name: newrelic
    description: New Relic packages for Enterprise Linux - $basearch
    baseurl: "{{ newrelic_php_yum_repo }}"
    gpgkey: "{{ newrelic_php_repo_key_url }}"

- name: install new relic php agent
  yum:
    name: "{{ newrelic_php_package }}"
    state: present
